-- Creating the database
CREATE DATABASE IF NOT EXISTS warframe;

-- Creating user and granting privileges
CREATE USER IF NOT EXISTS 'warframe_user'@'%' IDENTIFIED BY 'secure_password_123';
GRANT SELECT, INSERT, UPDATE, DELETE ON warframe.* TO 'warframe_user'@'%';

-- Using the database
USE warframe;

-- Creating the items table
CREATE TABLE IF NOT EXISTS items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

-- Creating the relics table with foreign keys
CREATE TABLE IF NOT EXISTS relics (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    common1 INT,
    common2 INT,
    common3 INT,
    uncommon1 INT,
    uncommon2 INT,
    rare INT,
    FOREIGN KEY (common1) REFERENCES items(id),
    FOREIGN KEY (common2) REFERENCES items(id),
    FOREIGN KEY (common3) REFERENCES items(id),
    FOREIGN KEY (uncommon1) REFERENCES items(id),
    FOREIGN KEY (uncommon2) REFERENCES items(id),
    FOREIGN KEY (rare) REFERENCES items(id)
);

-- Inserting testing data into items
INSERT INTO items (name, description) VALUES
('Forma', 'Used to polarize Warframe and weapon slots.'),
('Braton Prime Barrel', 'A component for the Braton Prime weapon.'),
('Braton Prime Receiver', 'A component for the Braton Prime weapon.'),
('Braton Prime Stock', 'A component for the Braton Prime weapon.'),
('Braton Prime Blueprint', 'A blueprint used for the Braton Prime weapon.'),
('Paris Prime String', 'A component for the Paris Prime weapon.'),
('Paris Prime Grip', 'A component for the Paris Prime weapon.'),
('Paris Prime Upper Limb', 'A component for the Paris Prime weapon.'),
('Paris Prime Lower Limb', 'A component for the Paris Prime weapon.'),
('Paris Prime Blueprint', 'A blueprint used for the Paris Prime weapon.'),
('Caliban Prime Neuroptics', 'A component for Caliban Prime.'),
('Caliban Prime Chassis', 'A component for Caliban Prime.'),
('Caliban Prime Systems', 'A component for Caliban Prime.'),
('Caliban Prime Blueprint', 'A blueprint used for Caliban Prime.'),
('Venato Prime Blade', 'A component for Venato Prime.'),
('Venato Prime Handle', 'A component for Venato Prime.'),
('Venato Prime Blueprint', 'A blueprint used for the Venato Prime.'),
('Vadarya Prime Barrel', 'A component for Vadarya Prime.'),
('Vadarya Prime Receiver', 'A component for Vadarya Prime.'),
('Vadarya Prime Stock', 'A component for Vadarya Prime.'),
('Vadarya Prime Blueprint', 'A blueprint used for the Vadarya Prime.'),
('Xaku Prime Neuroptics', 'A component for Xaku Prime.'),
('Xaku Prime Chassis', 'A component for Xaku Prime.'),
('Xaku Prime Systems', 'A component for Xaku Prime.'),
('Xaku Prime Blueprint', 'A blueprint used for Xaku Prime.'),
('Fang Prime Blade', 'A component for Fang Prime.'),
('Fang Prime Handle', 'A component for Fang Prime.'),
('Fang Prime Blueprint', 'A blueprint used for the Fang Prime.'),
('Velox Prime Barrel', 'A component for Vadarya Prime.'),
('Velox Prime Receiver', 'A component for Vadarya Prime.'),
('Velox Prime Blueprint', 'A blueprint used for the Velox Prime.'),
('Nautilus Prime Cerebrum', 'A component for Nautilus Prime.'),
('Nautilus Prime Carapace', 'A component for Nautilus Prime.'),
('Nautilus Prime Systems', 'A component for Nautilus Prime.'),
('Nautilus Prime Blueprint', 'A blueprint used for Nautilus Prime.'),
('Trumna Prime Barrel', 'A component for the Trumna Prime weapon.'),
('Trumna Prime Receiver', 'A component for the Trumna Prime weapon.'),
('Trumna Prime Stock', 'A component for the Trumna Prime weapon.'),
('Trumna Prime Blueprint', 'A blueprint used for the Trumna Prime weapon.'),
('Cedo Prime Barrel', 'A component for the Cedo Prime weapon.'),
('Cedo Prime Receiver', 'A component for the Cedo Prime weapon.'),
('Cedo Prime Stock', 'A component for the Cedo Prime weapon.'),
('Cedo Prime Blueprint', 'A blueprint used for the Cedo Prime weapon.'),
('Kompressa Prime Barrel', 'A component for Kompressa Prime.'),
('Kompressa Prime Receiver', 'A component for Kompressa Prime.'),
('Kompressa Prime Blueprint', 'A blueprint used for the Kompressa Prime.'),
('Gauss Prime Neuroptics', 'A component for Gauss Prime.'),
('Gauss Prime Chassis', 'A component for Gauss Prime.'),
('Gauss Prime Systems', 'A component for Gauss Prime.'),
('Gauss Prime Blueprint', 'A blueprint used for Gauss Prime.'),
('Bronco Prime Barrel', 'A component for Bronco Prime.'),
('Bronco Prime Receiver', 'A component for Bronco Prime.'),
('Bronco Prime Blueprint', 'A blueprint used for the Bronco Prime.'),
('Akbronco Prime Link', 'A component for Akbronco Prime.'),
('Akbronco Prime Blueprint', 'A blueprint used for the Akbronco Prime.'),
('Dual Zoren Prime Blade', 'A component for Dual Zoren Prime.'),
('Dual Zoren Prime Handle', 'A component for Dual Zoren Prime.'),
('Dual Zoren Prime Blueprint', 'A blueprint used for the Dual Zoren Prime.'),
('Lavos Prime Neuroptics', 'A component for Lavos Prime.'),
('Lavos Prime Chassis', 'A component for Lavos Prime.'),
('Lavos Prime Systems', 'A component for Lavos Prime.'),
('Lavos Prime Blueprint', 'A blueprint used for Lavos Prime.'),
('Epitaph Prime Barrel', 'A component for Epitaph Prime.'),
('Epitaph Prime Receiver', 'A component for Epitaph Prime.'),
('Epitaph Prime Blueprint', 'A blueprint used for the Epitaph Prime.'),
('Okina Prime Blade', 'A component for Okina Prime.'),
('Okina Prime Handle', 'A component for Okina Prime.'),
('Okina Prime Blueprint', 'A blueprint used for the Okina Prime.'),
('Daikyu Prime String', 'A component for the Daikyu Prime weapon.'),
('Daikyu Prime Grip', 'A component for the Daikyu Prime weapon.'),
('Daikyu Prime Upper Limb', 'A component for the Daikyu Prime weapon.'),
('Daikyu Prime Lower Limb', 'A component for the Daikyu Prime weapon.'),
('Daikyu Prime Blueprint', 'A blueprint used for the Daikyu Prime weapon.'),
('Sevagoth Prime Neuroptics', 'A component for Sevagoth Prime.'),
('Sevagoth Prime Chassis', 'A component for Sevagoth Prime.'),
('Sevagoth Prime Systems', 'A component for Sevagoth Prime.'),
('Sevagoth Prime Blueprint', 'A blueprint used for Sevagoth Prime.'),
('Protea Prime Neuroptics', 'A component for Protea Prime.'),
('Protea Prime Chassis', 'A component for Protea Prime.'),
('Protea Prime Systems', 'A component for Protea Prime.'),
('Protea Prime Blueprint', 'A blueprint used for Protea Prime.'),
('Acceltra Prime Barrel', 'A component for the Acceltra Prime weapon.'),
('Acceltra Prime Receiver', 'A component for the Acceltra Prime weapon.'),
('Acceltra Prime Stock', 'A component for the Acceltra Prime weapon.'),
('Acceltra Prime Blueprint', 'A blueprint used for the Acceltra Prime weapon.'),
('Quassus Prime Blade', 'A component for Quassus Prime.'),
('Quassus Prime Handle', 'A component for Quassus Prime.'),
('Quassus Prime Blueprint', 'A blueprint used for the Quassus Prime.'),
('Akarius Prime Barrel', 'A component for Akarius Prime.'),
('Akarius Prime Receiver', 'A component for Akarius Prime.'),
('Akarius Prime Link', 'A component for Akarius Prime.'),
('Akarius Prime Blueprint', 'A blueprint used for the Akarius Prime.'),
('Burston Prime Barrel', 'A component for the Burston Prime weapon.'),
('Burston Prime Receiver', 'A component for the Burston Prime weapon.'),
('Burston Prime Stock', 'A component for the Burston Prime weapon.'),
('Burston Prime Blueprint', 'A blueprint used for the Burston Prime weapon.');

-- Inserting testing data into relics (using item IDs from above)
INSERT INTO relics (name, common1, common2, common3, uncommon1, uncommon2, rare) VALUES
('Meso V11', 5, 22, 26, 34, 14, 29),
('Lith K12', 40, 12, 4, 1, 42, 45),
('Lith C13', 49, 53, 1, 59, 55, 11),
('Axi C10', 61, 66, 67, 1, 73, 13),
('Meso V12', 1, 30, 88, 78, 52, 21),
('Neo A15', 51, 1, 70, 89, 18, 83),
('Axi S18', 43, 1, 6, 31, 19, 76),
('Lith O4', 90, 20, 53, 79, 23, 69),
('Lith E2', 74, 77, 58, 17, 1, 65),
('Axi V13', 82, 33, 1, 48, 94, 15);
